server:
   port: 8093
   
spring:
   datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: admin
      password: admin
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
          path: /h2-console
          enabled: true
          settings:
             trace: false
             web-allow-others: true

security:
   oauth2:
      resource:
         jwt:
            key-value: sign-key-secret