version: '2.2'

services:
  config-service:
    container_name: config-service
    image: astro/config-service:Github-SNAPSHOT
    networks:
      - astro
    restart: always
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5

  discovery-service:
    container_name: discovery-service
    image: astro/discovery-service:Github-SNAPSHOT
    networks:
      - astro
    depends_on:
       config-service:
          condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5
      
  gateway-service:
    container_name: gateway-service
    image: astro/gateway-service:Github-SNAPSHOT
    networks:
      - astro
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    restart: always
    ports: 
      - "8764:8764"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8764/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5

  auth-service:
    container_name: auth-service
    image: astro/auth-service:Github-SNAPSHOT
    networks:
      - astro
    depends_on:
       config-service:
          condition: service_healthy
       discovery-service:
          condition: service_healthy
    ports: 
      - "8093:8093"
    restart: always
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8093/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5

  account-service:
    container_name: account-service
    image: astro/account-service:Github-SNAPSHOT
    networks:
      - astro
    depends_on:
       config-service:
          condition: service_healthy
       discovery-service:
          condition: service_healthy
    ports: 
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5

networks:
  astro:
    driver: bridge