spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

security:
  jwt:
    key-store: classpath:mykeystore.jks
    key-store-password: adminadmin
    key-pair-alias: servercert
    key-pair-password: adminadmin