version: '2.1'

services:
  config-service:
    container_name: config-service
    image: astro/config-service:Github-SNAPSHOT
    restart: always
    ports: 
      - "8888:8888"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5

  discovery-service:
    container_name: discovery-service
    image: astro/discovery-service:Github-SNAPSHOT
    depends_on:
      - config-service
    restart: always
    ports: 
      - "8761:8761"
    restart: on-failure
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 1m
      timeout: 3s
      retries: 5
      
  # gateway-service:
  #   build:
  #     context: gateway-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - config-service
  #     - discovery-service
  #   ports: 
  #     - "8764:8764"
  #   restart: on-failure

  # auth-service:
  #   build:
  #     context: auth-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - config-service
  #     - discovery-service
  #   ports: 
  #     - "8093:8093"
  #   restart: on-failure

  # account-service:
  #   build:
  #     context: account-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - config-service
  #     - discovery-service
  #   ports: 
  #     - "8000:8000"
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD","curl","-f","http://localhost:8000/"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20
  # networks:
  #     astro:
  #       # driver: bridge