version: '2.1'

services:
  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 20

  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    depends_on:
      - config-service
    ports: 
      - "8761:8761"
    restart: on-failure
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 20

  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    depends_on:
      - config-service
      - discovery-service
    ports: 
      - "8764:8764"
    restart: on-failure

  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    depends_on:
      - config-service
      - discovery-service
    ports: 
      - "8093:8093"
    restart: on-failure

  account-service:
    build:
      context: account-service
      dockerfile: Dockerfile
    depends_on:
      - config-service
      - discovery-service
    ports: 
      - "8000:8000"
    restart: on-failure
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/"]
      interval: 5s
      timeout: 5s
      retries: 20